name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  font_awesome_flutter: ^10.12.0
  video_player_android: ^2.9.1
  video_player_avfoundation: ^2.8.8
  video_player: ^2.10.1
  video_player_platform_interface: ^6.6.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  google_fonts: ^7.0.0
  smooth_page_indicator: ^2.0.1
  provider: ^6.1.5+1
  badges: ^3.1.2
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  flutter_paymob: ^1.0.8
  http: ^1.6.0
  intl: ^0.20.2
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_secure_storage: ^10.0.0
  device_info_plus: ^12.3.0
  uuid: ^4.5.2
  local_auth: ^3.0.0
  flutter_local_notifications: ^19.5.0
  firebase_auth: ^6.1.3
  jwt_decoder: ^2.0.1
  # test

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/home/
    - assets/icons/
