name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  font_awesome_flutter: ^10.12.0
  video_player_android: ^2.9.1
  video_player_avfoundation: ^2.8.8
  video_player: ^2.10.1
  video_player_platform_interface: ^6.6.0
  carousel_slider: ^5.1.1
  woocommerce_flutter_api: ^1.1.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.3
  smooth_page_indicator: ^2.0.1
  provider: ^6.1.5+1
  badges: ^3.1.2
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/home/
    - assets/products/
    - assets/brands/
    - assets/icons/
